### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by alexandzors** [NathanVaughn/actions-cloudflare-purge#46]
Not sure what's going on here but I can't seem to get this action to work. I have the zone id for the site set properly and the API token  has cache purge permissions for the zone. Every time I run the action it fails with the error `urllib.error.HTTPError: HTTP Error 400: Bad Request` during my build process for my blog.

**Actions Log**
```
Run nathanvaughn/***-cloudflare-purge@master
  with:
    cf_zone: ***
    cf_auth: ***
    hosts: ***
/usr/bin/docker run --name e547a168fcf780a4a47bfafa27737a14dea_a60823 --label 675e54 --workdir /github/workspace --rm -e "INPUT_CF_ZONE" -e "INPUT_CF_AUTH" -e "INPUT_HOSTS" -e "INPUT_URLS" -e "INPUT_FILES" -e "INPUT_TAGS" -e "INPUT_PREFIXES" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/blog/blog":"/github/workspace" 675e54:7a168fcf780a4a47bfafa27737a14dea  "--cf-zone=***" "--cf-auth=***" "--urls" "" "--files" "" "--tags" "" "--hosts" "***" "--prefixes" ""
Traceback (most recent call last):
  File "/app/main.py", line 149, in <module>
    main()
  File "/app/main.py", line 134, in main
Request:
https://api.cloudflare.com/client/v4/zones/***/purge_cache
Headers:
{
    "Authorization": "***",
    "Content-Type": "application/json",
    "User-Agent": "github.com/nathanvaughn/***-cloudflare-purge"
}
Payload:
{
    "hosts": [
        "***"
    ]
}
    resp = request.urlopen(req)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Actions file**
```yml
      - name: Purge Cloudflare Cache
        if: (steps.deploy.outcome  == 'success')
        uses: nathanvaughn/actions-cloudflare-purge@master
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE_DEV }}
          cf_auth: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          hosts: ${{ secrets.DEVURL_NOHTTPS }}
```

**Secret Setup**
This is an example of how my secrets are setup to show I only have them and no extra data present.. *redacted of course*
CLOUDFLARE_ZONE_DEV = `xxxxxxxxxxxxxxxxxxxxxxxxxx6e95`
CLOUDFLARE_API_TOKEN = `xxxxxxxxxxxxxxxxxxxxxxxxxx236x`
DEVURL_NOHTTPS = `blog.mydomain.com`

**Comment by NathanVaughn** [comment]
Thanks for pointing this out. I have just pushed an update now so that the response from Cloudflare is shown on failure.
If I were to bet here, you probably don't have an Enterprise account. 
![image](https://github.com/NathanVaughn/actions-cloudflare-purge/assets/8636459/5a35ba37-4b7e-4cd3-852d-52c966b1302a)

**Comment by alexandzors** [comment]
Haha yeah I don't. Probably should have read the Cloudflare API docs....
